### ISSUE TITLE
LMSmonitor in piCorePlayer

### ISSUE THREAD

**Issue by willefg** [kabavol/LMSMonitor#1]
I have an issue installing LMSmonitor in piCorePlayer. As I’m not a programmer I normally get by following detailed instructions step by step. I followed the readme instructions, so copying the the 2 files in the designated folder and added the line in Tweaks page of pCp.
That didn’t make my SH1106 OLED display anything...
I assumed I needed i2c-tools so I installed the extension. I also assume pCp needs other libraries or extensions. Can you help me with the installation, please?

**Comment by DeviousPenguin** [comment]
What does it say then you run the .sh file?

**Comment by willefg** [comment]
As it is exactly one year ago, today, I wouldn’t know. I’ve moved to DietPi with Squeezelite and pydPiper and that works great. I’ll close the issue.
