### ISSUE TITLE
Compatibility with screen HD44780

### ISSUE THREAD

**Issue by GG700** [kabavol/LMSMonitor#4]
Hi,

LMSMonitor is compatible with HD44780 screens ?
This screen is in RASPDAC.
[https://www.audiophonics.fr/fr/ecrans-afficheurs-vu-metres/winstar-weh001602a-ecran-oled-16x2-blanc-hd44780-p-8512.html]

Thnks for your reply,
Jerome

**Comment by kabavol** [comment]
Hi Jerome,
No, this version only support some I2C oled displays. I will no update this code in the future, so please check (shunte88's fork)[https://github.com/shunte88/LMSMonitor], wich is a living project.
Best regards,
  Laszlo
