### ISSUE TITLE
Sintax

### ISSUE THREAD

**Issue by JRM-PT** [kabavol/LMSMonitor#5]
Could you please write the correct sintax of all commands and parameters?

**Comment by kabavol** [comment]
Hi JRM-PT,

The bin/LMSMonitor_v03_bin.tgz contains a short shell scrip. It is good example to start lmsmonitor. You can find the valid options in README.md.
I will no update this code in the future, so please check (shunte88's fork)[https://github.com/shunte88/LMSMonitor], wich is a living project.

Best regards,
  Laszlo

**Comment by JRM-PT** [comment]
Thanks. I understood that shunte88's fork was the live one and thought to ask the question to him but it looks that I've messed up.
